    
    
    
    <!-- jQuery -->
    <script src="./assets/frontend/views/admin/_libs/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="./assets/frontend/views/admin/_libs/bootstrap/js/bootstrap.min.js"></script>
    <script src="./assets/frontend/views/admin/_libs/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
    
    <!-- Notify -->
    <script src="./assets/frontend/views/admin/_libs/js/notify.js"></script>    

    <!-- Metis Menu Plugin JavaScript -->
    <script src="./assets/frontend/views/admin/_libs/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="./assets/frontend/views/admin/_libs/js/sb-admin-2.js"></script>
    
    <!-- Core JavaScript -->
    <script src="./assets/frontend/views/admin/_libs/js/core.js"></script>    