
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>PANDIX - PHP and Interface Experience</title>

<!-- Bootstrap Core CSS -->
<link href="./assets/frontend/views/admin/_libs/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="./assets/frontend/views/admin/_libs/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet">

<!-- MetisMenu CSS -->
<link href="./assets/frontend/views/admin/_libs/metisMenu/metisMenu.min.css" rel="stylesheet">

<!-- Custom CSS -->
<link href="./assets/frontend/views/admin/_libs/css/sb-admin-2.css" rel="stylesheet">

<!-- Custom Fonts -->
<link href="./assets/frontend/views/admin/_libs/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="./assets/frontend/views/admin/_libs/js/html5shiv.js"></script>
    <script src="./assets/frontend/views/admin/_libs/js/respond.min.js"></script>
<![endif]-->

